const countryOptions =  
[
  {value: 'US', text: 'United States'},
  {value: 'CA-AB', text: 'Alberta'},
  {value: 'AL', text: 'Albania'},
  {value: 'AT', text: 'Austria'},
  {value: 'BY', text: 'Belarus'},
  {value: 'BE', text: 'Belgium'},
  {value: 'BA', text: 'Bosnia and Herzegovina'},
  {value: 'CA-BC', text: 'British Columbia'},
  {value: 'BG', text: 'Bulgaria'},
  {value: 'HR', text: 'Croatia'},
  {value: 'CZ', text: 'Czech Republic'},
  {value: 'DK', text: 'Denmark'},
  {value: 'EE', text: 'Estonia'},
  {value: 'FO', text: 'Faroe Islands'},
  {value: 'FI', text: 'Finland'},
  {value: 'FR', text: 'France'},
  {value: 'DE', text: 'Germany'},
  {value: 'GR', text: 'Greece'},
  {value: 'HU', text: 'Hungary'},
  {value: 'IT', text: 'Italy'},
  {value: 'LV', text: 'Latvia'},
  {value: 'LT', text: 'Lithuania'},
  {value: 'RU-KGD', text: 'Kaliningradskaya oblast'},
  {value: 'MK', text:'Macedonia'},
  {value: 'ME', text: 'Montenegro'},
  {value: 'NL', text: 'Netherlands'},
  {value: 'CA-NB', text: 'New Brunswick'},
  {value: 'CA-ON', text: 'Ontario'},
  {value: 'PE', text: 'Peru'},
  {value: 'PL', text: 'Poland'},
  {value: 'PT', text: 'Portugal'},
  {value: 'CA-PE', text: 'Prince Edward Island'},
  {value: 'IE', text: 'Republic of Ireland'},
  {value: 'RO', text: 'Romania'},
  {value: 'RU', text: 'Russia'},
  {value: 'RS', text: 'Serbia'},
  {value: 'SK', text: 'Slovakia'},
  {value: 'SI', text: 'Slovenia'},
  {value: 'ES', text: 'Spain'},
  {value: 'SE', text: 'Sweden'},
  {value: 'CH', text: 'Switzerland'},
  {value: 'TW', text: 'Taiwan'},
  {value: 'TR', text: 'Turkey'},
  {value: 'UA', text: 'Ukraine'},
  {value: 'CA-YT', text: 'Yukon'}
];

module.exports = countryOptions;

